<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_acceso
* GENERATION DATE:  27.01.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_acceso.php
* FOR MYSQL TABLE:  acceso
* FOR MYSQL DB:     servicios
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_acceso
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_acceso;   // KEY ATTR. WITH AUTOINCREMENT

var $rut_cliente;   // (normal Attribute)
var $pwd_actual;   // (normal Attribute)
var $pwd_last;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_acceso()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_acceso()
{
return $this->id_acceso;
}

function getrut_cliente()
{
return $this->rut_cliente;
}

function getpwd_actual()
{
return $this->pwd_actual;
}

function getpwd_last()
{
return $this->pwd_last;
}

// **********************
// SETTER METHODS
// **********************


function setid_acceso($val)
{
$this->id_acceso =  $val;
}

function setrut_cliente($val)
{
$this->rut_cliente =  $val;
}

function setpwd_actual($val)
{
$this->pwd_actual =  $val;
}

function setpwd_last($val)
{
$this->pwd_last =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM acceso WHERE id_acceso = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_acceso = $row->id_acceso;

$this->rut_cliente = $row->rut_cliente;

$this->pwd_actual = $row->pwd_actual;

$this->pwd_last = $row->pwd_last;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM acceso WHERE id_acceso = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_acceso = ""; // clear key for autoincrement

$sql = "INSERT INTO acceso ( rut_cliente,pwd_actual,pwd_last ) VALUES ( '$this->rut_cliente','$this->pwd_actual','$this->pwd_last' )";
$result = $this->database->consulta($sql);
$this->id_acceso = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE acceso SET  rut_cliente = '$this->rut_cliente',pwd_actual = '$this->pwd_actual',pwd_last = '$this->pwd_last' WHERE id_acceso = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>