<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_categoria
* GENERATION DATE:  27.01.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_categoria.php
* FOR MYSQL TABLE:  categoria
* FOR MYSQL DB:     servicios
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_categoria
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_categoria;   // KEY ATTR. WITH AUTOINCREMENT

var $cat_id_categoria;   // (normal Attribute)
var $nombre_categoria;   // (normal Attribute)
var $descripcion_categoria;   // (normal Attribute)
var $arrcategoria;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_categoria()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_categoria()
{
return $this->id_categoria;
}

function getcat_id_categoria()
{
return $this->cat_id_categoria;
}

function getnombre_categoria()
{
return $this->nombre_categoria;
}

function getdescripcion_categoria()
{
return $this->descripcion_categoria;
}

// **********************
// SETTER METHODS
// **********************


function setid_categoria($val)
{
$this->id_categoria =  $val;
}

function setcat_id_categoria($val)
{
$this->cat_id_categoria =  $val;
}

function setnombre_categoria($val)
{
$this->nombre_categoria =  $val;
}

function setdescripcion_categoria($val)
{
$this->descripcion_categoria =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select()
{

$sql =  "SELECT * FROM categoria order by nombre_categoria;";
$result =  $this->database->consulta($sql);
$i=0;
while($row = $this->database->fetch_array($result)){

    $this->arrcategoria[$i]['id_categoria'] = $row->id_categoria;
    $this->arrcategoria[$i]['cat_id_categoria'] = $row->cat_id_categoria;
    $this->arrcategoria[$i]['nombre_categoria'] = $row->nombre_categoria;
    $this->arrcategoria[$i]['descripcion_categoria'] = $row->descripcion_categoria;
    $i++;
}
}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM categoria WHERE id_categoria = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_categoria = ""; // clear key for autoincrement

$sql = "INSERT INTO categoria ( cat_id_categoria,nombre_categoria,descripcion_categoria ) VALUES ( '$this->cat_id_categoria','$this->nombre_categoria','$this->descripcion_categoria' )";
$result = $this->database->consulta($sql);
$this->id_categoria = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE categoria SET  cat_id_categoria = '$this->cat_id_categoria',nombre_categoria = '$this->nombre_categoria',descripcion_categoria = '$this->descripcion_categoria' WHERE id_categoria = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>