<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_cliente
* GENERATION DATE:  27.01.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_cliente.php
* FOR MYSQL TABLE:  cliente
* FOR MYSQL DB:     servicios
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_cliente
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $rut_cliente;   // KEY ATTR. WITH AUTOINCREMENT

var $dvrut_cliente;   // (normal Attribute)
var $razon_cliente;   // (normal Attribute)
var $log_cliente;   // (normal Attribute)
var $giro_cliente;   // (normal Attribute)
var $condicion_pago;   // (normal Attribute)
var $fono_cliente;   // (normal Attribute)
var $email_cliente;   // (normal Attribute)
var $contacto;   // (normal Attribute)
var $nombre_fantasia;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_cliente()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getrut_cliente()
{
return $this->rut_cliente;
}

function getdvrut_cliente()
{
return $this->dvrut_cliente;
}

function getrazon_cliente()
{
return $this->razon_cliente;
}

function getlog_cliente()
{
return $this->log_cliente;
}

function getgiro_cliente()
{
return $this->giro_cliente;
}

function getcondicion_pago()
{
return $this->condicion_pago;
}

function getfono_cliente()
{
return $this->fono_cliente;
}

function getemail_cliente()
{
return $this->email_cliente;
}

function getcontacto()
{
return $this->contacto;
}

function getnombre_fantasia()
{
return $this->nombre_fantasia;
}

// **********************
// SETTER METHODS
// **********************


function setrut_cliente($val)
{
$this->rut_cliente =  $val;
}

function setdvrut_cliente($val)
{
$this->dvrut_cliente =  $val;
}

function setrazon_cliente($val)
{
$this->razon_cliente =  $val;
}

function setlog_cliente($val)
{
$this->log_cliente =  $val;
}

function setgiro_cliente($val)
{
$this->giro_cliente =  $val;
}

function setcondicion_pago($val)
{
$this->condicion_pago =  $val;
}

function setfono_cliente($val)
{
$this->fono_cliente =  $val;
}

function setemail_cliente($val)
{
$this->email_cliente =  $val;
}

function setcontacto($val)
{
$this->contacto =  $val;
}

function setnombre_fantasia($val)
{
$this->nombre_fantasia =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cliente WHERE rut_cliente = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->rut_cliente = $row->rut_cliente;

$this->dvrut_cliente = $row->dvrut_cliente;

$this->razon_cliente = $row->razon_cliente;

$this->log_cliente = $row->log_cliente;

$this->giro_cliente = $row->giro_cliente;

$this->condicion_pago = $row->condicion_pago;

$this->fono_cliente = $row->fono_cliente;

$this->email_cliente = $row->email_cliente;

$this->contacto = $row->contacto;

$this->nombre_fantasia = $row->nombre_fantasia;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cliente WHERE rut_cliente = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->rut_cliente = ""; // clear key for autoincrement

$sql = "INSERT INTO cliente ( dvrut_cliente,razon_cliente,giro_cliente,condicion_pago,fono_cliente,email_cliente,contacto,nombre_fantasia ) VALUES ( '$this->dvrut_cliente','$this->razon_cliente','$this->giro_cliente','$this->condicion_pago','$this->fono_cliente','$this->email_cliente','$this->contacto','$this->nombre_fantasia' )";
$result = $this->database->consulta($sql);
$this->rut_cliente = mysql_insert_id();

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cliente SET  dvrut_cliente = '$this->dvrut_cliente',razon_cliente = '$this->razon_cliente',giro_cliente = '$this->giro_cliente',condicion_pago = '$this->condicion_pago',fono_cliente = '$this->fono_cliente',email_cliente = '$this->email_cliente',contacto = '$this->contacto',nombre_fantasia = '$this->nombre_fantasia' WHERE rut_cliente = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>