<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_cotizacion
* GENERATION DATE:  27.01.2018
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_cotizacion.php
* FOR MYSQL TABLE:  cotizacion
* FOR MYSQL DB:     servicios
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/Conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_cotizacion
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_cotizacion;   // KEY ATTR. WITH AUTOINCREMENT

var $id_cotizacion_;   // (normal Attribute)
var $rut_cliente;   // (normal Attribute)
var $direccion_sucursal;   // (normal Attribute)
var $impuesto_cotizacion;   // (normal Attribute)
var $descuento_dpedidol;   // (normal Attribute)
var $estado_cotizacion;   // (normal Attribute)
var $impuesto_total_dpedido;   // (normal Attribute)
var $total_cotizacion;   // (normal Attribute)
var $fecha_cotizacion;   // (normal Attribute)
var $log_cotizacion;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_cotizacion()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_cotizacion_()
{
return $this->id_cotizacion_;
}

function getrut_cliente()
{
return $this->rut_cliente;
}

function getdireccion_sucursal()
{
return $this->direccion_sucursal;
}

function getimpuesto_cotizacion()
{
return $this->impuesto_cotizacion;
}

function getdescuento_dpedidol()
{
return $this->descuento_dpedidol;
}

function getestado_cotizacion()
{
return $this->estado_cotizacion;
}

function getimpuesto_total_dpedido()
{
return $this->impuesto_total_dpedido;
}

function gettotal_cotizacion()
{
return $this->total_cotizacion;
}

function getfecha_cotizacion()
{
return $this->fecha_cotizacion;
}

function getlog_cotizacion()
{
return $this->log_cotizacion;
}

// **********************
// SETTER METHODS
// **********************


function setid_cotizacion_($val)
{
$this->id_cotizacion_ =  $val;
}

function setrut_cliente($val)
{
$this->rut_cliente =  $val;
}

function setdireccion_sucursal($val)
{
$this->direccion_sucursal =  $val;
}

function setimpuesto_cotizacion($val)
{
$this->impuesto_cotizacion =  $val;
}

function setdescuento_dpedidol($val)
{
$this->descuento_dpedidol =  $val;
}

function setestado_cotizacion($val)
{
$this->estado_cotizacion =  $val;
}

function setimpuesto_total_dpedido($val)
{
$this->impuesto_total_dpedido =  $val;
}

function settotal_cotizacion($val)
{
$this->total_cotizacion =  $val;
}

function setfecha_cotizacion($val)
{
$this->fecha_cotizacion =  $val;
}

function setlog_cotizacion($val)
{
$this->log_cotizacion =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM cotizacion WHERE id_cotizacion = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_cotizacion_ = $row->id_cotizacion_;

$this->rut_cliente = $row->rut_cliente;

$this->direccion_sucursal = $row->direccion_sucursal;

$this->impuesto_cotizacion = $row->impuesto_cotizacion;

$this->descuento_dpedidol = $row->descuento_dpedidol;

$this->estado_cotizacion = $row->estado_cotizacion;

$this->impuesto_total_dpedido = $row->impuesto_total_dpedido;

$this->total_cotizacion = $row->total_cotizacion;

$this->fecha_cotizacion = $row->fecha_cotizacion;

$this->log_cotizacion = $row->log_cotizacion;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM cotizacion WHERE id_cotizacion = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_cotizacion = ""; // clear key for autoincrement

$sql = "INSERT INTO cotizacion ( id_cotizacion_,rut_cliente,direccion_sucursal,impuesto_cotizacion,descuento_dpedidol,estado_cotizacion,impuesto_total_dpedido,total_cotizacion,fecha_cotizacion,log_cotizacion ) VALUES ( '$this->id_cotizacion_','$this->rut_cliente','$this->direccion_sucursal','$this->impuesto_cotizacion','$this->descuento_dpedidol','$this->estado_cotizacion','$this->impuesto_total_dpedido','$this->total_cotizacion','$this->fecha_cotizacion','$this->log_cotizacion' )";
$result = $this->database->consulta($sql);
$this->id_cotizacion = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE cotizacion SET  id_cotizacion_ = '$this->id_cotizacion_',rut_cliente = '$this->rut_cliente',direccion_sucursal = '$this->direccion_sucursal',impuesto_cotizacion = '$this->impuesto_cotizacion',descuento_dpedidol = '$this->descuento_dpedidol',estado_cotizacion = '$this->estado_cotizacion',impuesto_total_dpedido = '$this->impuesto_total_dpedido',total_cotizacion = '$this->total_cotizacion',fecha_cotizacion = '$this->fecha_cotizacion',log_cotizacion = '$this->log_cotizacion' WHERE id_cotizacion = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>